//authorization
export const START_LOADING = 'START_LOADING';
export const FINISH_LOADING = 'FINISH_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_START = 'AUTH_START';
export const LOGIN = 'LOGIN';
export const LOGIN_LOCALY = 'LOGIN_LOCALY';
export const RESET_TIMEOUT_ID = 'RESET_TIMEOUT_ID';
export const SET_TOKEN = 'SET_TOKEN';
export const LOGOUT = 'LOGOUT';

//band
export const SET_BAND_DATA = 'SET_BAND_DATA';
export const BAND_ERROR = 'BAND_ERROR';
export const CLEAR_BAND_DATA = 'CLEAR_BAND_DATA';
export const FINISH_BAND_LOADING = 'FINISH_BAND_LOADING';
export const START_BAND_UPDATING = 'START_BAND_UPDATING';
export const FINISH_BAND_UPDATING = 'FINISH_BAND_UPDATING';

//song
export const START_SONG_CREATION = 'START_SONG_CREATION';
export const FINISH_SONG_CREATION = 'FINISH_SONG_CREATION';
export const START_SONGS_LOADING = 'START_SONGS_LOADING';
export const FINISH_SONGS_LOADING = 'FINISH_SONGS_LOADING';
export const SONGS_ERROR = 'SONGS_ERROR';
export const SET_LOAD_PERCENTS = 'SET_LOAD_PERCENTS';
export const UNSHIFT_SONG_TO_LIST = 'UNSHIFT_SONG_TO_LIST';
export const ADD_SONGS_TO_LIST = 'ADD_SONGS_TO_LIST';
export const CLEAR_SONGS_LIST = 'CLEAR_SONGS_LIST';
export const SELECT_SONG = 'SELECT_SONG';
export const PLAY_RECIVED_SONG = 'PLAY_RECIVED_SONG';
export const SELECT_NEXT_SONG = 'SELECT_NEXT_SONG';
export const SELECT_PREV_SONG = 'SELECT_PREV_SONG';
export const PLAY_SONG = 'PLAY_SONG';
export const PAUSE_SONG = 'PAUSE_SONG';
export const SELECTED_SONG_READY_TO_PLAY = 'SELECTED_SONG_READY_TO_PLAY';
export const CHANGE_SELECTED_GENRE = 'CHANGE_SELECTED_GENRE';
export const TOGGLE_SONG_LIKES = 'TOGGLE_SONG_LIKES';
export const START_SONG_UPDATING = 'START_SONG_UPDATING';
export const FINISH_SONG_UPDATING = 'FINISH_SONG_UPDATING';
export const SET_SONG_UPDATED_DATA = 'SET_SONG_UPDATED_DATA';
export const ADD_PLAYLISTS = 'ADD_PLAYLISTS';
export const CLEAR_PLAYLISTS = 'CLEAR_PLAYLISTS';
export const SHUFFLE_SONGS = 'SHUFFLE_SONGS';

