//authorization
export const START_LOADING = 'START_LOADING';
export const FINISH_LOADING = 'FINISH_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_START = 'AUTH_START';
export const LOGIN = 'LOGIN';
export const LOGIN_LOCALY = 'LOGIN_LOCALY';
export const RESET_TIMEOUT_ID = 'RESET_TIMEOUT_ID';
export const SET_TOKEN = 'SET_TOKEN';
export const LOGOUT = 'LOGOUT';

//band
export const SET_BAND_DATA = 'SET_BAND_DATA';
export const BAND_ERROR = 'BAND_ERROR';
export const CLEAR_BAND_DATA = 'CLEAR_BAND_DATA';
export const FINISH_BAND_LOADING = 'FINISH_BAND_LOADING';
export const START_BAND_UPDATING = 'START_BAND_UPDATING';
export const FINISH_BAND_UPDATING = 'FINISH_BAND_UPDATING';

//song
export const ADD_SONG = 'ADD_SONG';
export const START_SONG_CREATION = 'START_SONG_CREATION';
export const FINISH_SONG_CREATION = 'FINISH_SONG_CREATION';
export const FINISH_SONGS_LOADING = 'FINISH_SONGS_LOADING';
export const SONGS_ERROR = 'SONGS_ERROR';
export const SET_LOAD_PERCENTS = 'SET_LOAD_PERCENTS';

